export type Block =
  | { t: 'p'; v: string }
  | { t: 'h2'; v: string }
  | { t: 'h3'; v: string }
  | { t: 'quote'; v: string; author?: string }
  | { t: 'ul'; v: string[] }
  | { t: 'ol'; v: string[] }
  | { t: 'highlight'; v: string }
  | { t: 'hr' }

export interface Article {
  slug: string
  id: number
  category: string
  date: string
  readTime: string
  title: string
  excerpt: string
  cover: string
  author: { initials: string; name: string; role: string; bg: string }
  blocks: Block[]
}

// HIDDEN — article fictif (cas d'usage illustratif, pas un vrai client)
// Pour remettre en ligne : déplacer cet objet dans BLOG_ARTICLES ci-dessous
export const HIDDEN_BLOG_ARTICLES: Article[] = [
  {
    slug: '3-avis-50000-euros',
    id: 0,
    category: 'Étude de cas',
    date: '19 mai 2026',
    readTime: '10 min',
    title: "Comment 3 avis Google ont coûté 50 000 € à un bistrot parisien.",
    excerpt: "On a passé 3 semaines à éplucher les comptes d'un restaurant du 11e qui est passé de 4,5 à 3,9 étoiles. La baisse de réservations a été plus rapide et plus brutale que tout ce qu'on avait imaginé.",
    cover: 'orange-block',
    author: { initials: 'YG', name: 'Yann Grigoriev', role: 'CEO, Splitzy', bg: '#E8920A' },
    blocks: [
      { t: 'p', v: "Le Bistrot du Faubourg est un restaurant comme il en existe des centaines à Paris. 40 couverts, cuisine du marché, terrasse en été. En janvier 2025, sa note Google était de 4,5 étoiles sur 187 avis. Une note acquise en trois ans de travail régulier, de produits soignés et d'une salle qui revient." },
      { t: 'p', v: "En avril 2025, sa note était de 3,9. La réservation en ligne avait chuté de 34 %. Le gérant, Karim, estimait avoir perdu entre 40 000 et 60 000 € de chiffre d'affaires sur le trimestre. Tout ça à cause de 3 avis." },
      { t: 'h2', v: "Semaine 1 : le premier avis" },
      { t: 'p', v: "Le 12 janvier au soir, un groupe de 6 personnes dîne au Bistrot du Faubourg. Le service est long — une table de 8 est arrivée en retard et a bousculé la cadence de la cuisine. Le groupe attend 35 minutes entre l'entrée et le plat. Ça arrive." },
      { t: 'p', v: "À 22h17, depuis le métro ligne 3, l'un d'eux ouvre Google Maps et laisse un avis 1 étoile : « Service catastrophique. On a attendu 40 minutes pour nos plats. Le serveur ne s'est même pas excusé. À éviter. »" },
      { t: 'p', v: "Karim voit l'avis le lendemain matin. Il répond : « Votre remarque est inexacte. Nous avons eu un incident en cuisine ce soir-là, ce qui est exceptionnel. Notre équipe est professionnelle. » Le ton est défensif. Le sous-texte est clair : c'est votre faute." },
      { t: 'p', v: "Google affiche maintenant les deux — l'avis et la réponse — en vitrine pour tous les futurs clients." },
      { t: 'h2', v: "Semaine 2 : l'effet boule de neige" },
      { t: 'p', v: "Le 21 janvier, une autre table mécontente — cette fois le bœuf était trop cuit — laisse à son tour un avis 1 étoile. Puis un troisième le 28 janvier, sur un sujet différent : « Bruyant, tables trop serrées, on s'est sentis pressés de partir. »" },
      { t: 'p', v: "Trois avis négatifs en 16 jours. La note de Google passe de 4,5 à 4,1. Ce n'est pas dramatique en apparence. Mais l'algorithme de Google Maps a enregistré le signal." },
      { t: 'highlight', v: "Sur Google Maps, les restaurants dont la note baisse voient leur positionnement dans les résultats de recherche reculer dans les 48 à 72 heures qui suivent. Ce n'est pas documenté officiellement. Nos tests le confirment." },
      { t: 'p', v: "À la fin de la semaine 2, une réservation de 8 personnes pour un anniversaire — prise sur La Fourchette — est annulée. Dans le message : « On a vu vos récents avis. On préfère aller ailleurs. »" },
      { t: 'h2', v: "Le calcul des 50 000 €" },
      { t: 'p', v: "Karim nous a ouvert ses données sur 90 jours. Voici ce qu'on a mesuré :" },
      { t: 'ul', v: [
        "Baisse de réservations en ligne : −34 %",
        "Nombre de couverts perdus sur 3 mois : environ 420",
        "Ticket moyen au Bistrot du Faubourg : 38 € par personne",
        "Chiffre d'affaires non réalisé (conservateur) : 420 × 38 = 15 960 €",
        "Sur 6 mois en projetant la tendance : environ 50 000 €",
      ]},
      { t: 'p', v: "Ce calcul est conservateur. Il ne prend pas en compte les clients qui ne réservent pas mais qui passent devant et décident de ne pas entrer en voyant la note sur leur téléphone. Il ne prend pas non plus en compte la perte de clients fidèles qui, en voyant la baisse de note, commencent à explorer d'autres options." },
      { t: 'h2', v: "Ce qui aurait dû se passer" },
      { t: 'p', v: "Le groupe du 12 janvier était mécontent. C'est légitime. Ils ont attendu trop longtemps. Le problème n'est pas qu'ils étaient mécontents — le problème est qu'ils n'ont eu aucune occasion d'exprimer leur mécontentement en privé." },
      { t: 'p', v: "Si, au moment de payer, Splitzy leur avait demandé « Comment s'est passé votre soirée ? » avec une interface discrète et non intrusive, deux scénarios étaient possibles :" },
      { t: 'ol', v: [
        "Ils notent 3/5, écrivent leur frustration dans le champ texte. Le message arrive directement à Karim. Karim répond dans l'heure. Propose un geste commercial. Le client repart avec une impression différente. Il ne poste rien sur Google.",
        "Ils cliquent sans répondre. Pas de feedback. Pas d'avis. Rien.",
      ]},
      { t: 'quote', v: "Le problème n'est pas que des clients soient mécontents. Le problème, c'est qu'ils n'ont nulle part d'autre où aller que Google.", author: "Karim B., Le Bistrot du Faubourg" },
      { t: 'h2', v: "La suite pour le Bistrot du Faubourg" },
      { t: 'p', v: "Karim a installé Splitzy en mars 2025. En six semaines, il avait collecté 84 feedbacks privés. Dont 11 négatifs — tous traités en direct, aucun posté publiquement. Sa note Google est remontée à 4,3 en juillet 2025, portée par 26 nouveaux avis positifs de clients satisfaits qui avaient été invités à laisser une note." },
      { t: 'p', v: "50 000 €. Pour 3 avis. Qui auraient pu ne jamais exister." },
    ],
  },

  // HIDDEN — comparatif Sunday/Pleez/Obypay (données fictives, 6 mois d'usage non réels)
  {
    slug: 'comparatif-sunday-pleez-obypay',
    id: 1,
    category: 'Comparatif',
    date: '14 mai 2026',
    readTime: '8 min',
    title: "Sunday, Pleez, Obypay : on a comparé honnêtement.",
    excerpt: "Frais cachés, expérience client, qualité du dashboard. Le verdict après 6 mois d'usage des 3 outils en parallèle.",
    cover: 'stripes-warm',
    author: { initials: 'TJ', name: 'Théo Jamous', role: 'CPO, Splitzy', bg: '#0A0A0A' },
    blocks: [
      { t: 'p', v: "Disclaimer d'abord : nous sommes Splitzy. Nous avons donc un intérêt évident à nous positionner favorablement dans ce comparatif. On va essayer d'être honnêtes. Vous jugerez." },
      { t: 'p', v: "On a passé 6 mois à utiliser Sunday, Pleez et Obypay dans des restaurants partenaires — avec leur accord. On a mesuré 6 critères : setup, coût mensuel, UX client, dashboard gérant, support, et gestion des feedbacks négatifs. Ce dernier point, c'est notre angle. Ce n'est pas un hasard." },
      { t: 'h2', v: "Sunday" },
      { t: 'p', v: "Sunday est le leader du marché en France. Leur UX client est la meilleure du secteur — le flow de paiement est propre, rapide, bien conçu. Ils ont levé beaucoup d'argent et ça se voit sur le produit." },
      { t: 'ul', v: [
        "Setup : 2-3 jours (intégration POS requise dans la plupart des cas)",
        "Coût : à partir de 49 €/mois + 0,5 % de commission sur chaque transaction",
        "UX client : excellente",
        "Dashboard gérant : correct, analytics basiques",
        "Support : réactif, équipe disponible",
        "Gestion des feedbacks négatifs : absente",
      ]},
      { t: 'p', v: "Ce dernier point mérite qu'on s'y attarde. Sunday collecte des notes NPS après chaque paiement. Mais quand un client note 1/5, que se passe-t-il ? La note va dans le dashboard. C'est tout. Il n'y a aucun mécanisme pour intercepter ce client avant qu'il aille sur Google." },
      { t: 'h2', v: "Pleez" },
      { t: 'p', v: "Pleez est fort sur l'intégration POS — ils couvrent Lightspeed, Revel, et plusieurs autres. Si votre caisse est compatible, le setup est fluide. Sinon, comptez sur une intégration manuelle." },
      { t: 'ul', v: [
        "Setup : 1 à 5 jours selon la caisse",
        "Coût : à partir de 69 €/mois, pas de commission",
        "UX client : fonctionnelle, moins soignée que Sunday",
        "Dashboard gérant : le plus complet du marché sur la gestion de tables",
        "Support : lent (48h en moyenne dans nos tests)",
        "Gestion des feedbacks négatifs : absente",
      ]},
      { t: 'p', v: "Pleez est un bon outil pour les gérants qui veulent une vue précise sur leurs opérations. Ce n'est pas un outil de réputation." },
      { t: 'h2', v: "Obypay" },
      { t: 'p', v: "Le moins cher des trois. Obypay cible les petites structures avec un budget serré. Le produit est basique, l'intégration simple, le résultat fonctionnel." },
      { t: 'ul', v: [
        "Setup : 24-48h",
        "Coût : à partir de 29 €/mois",
        "UX client : acceptable, quelques frictions",
        "Dashboard gérant : très basique",
        "Support : email uniquement, délais variables",
        "Gestion des feedbacks négatifs : absente",
      ]},
      { t: 'h2', v: "Et Splitzy ?" },
      { t: 'p', v: "On ne va pas se cacher derrière notre pudeur. Splitzy est plus récent. Notre UX client est bonne mais pas encore au niveau de Sunday. Notre intégration POS est en cours de déploiement. Voilà ce qu'on a." },
      { t: 'p', v: "Ce qu'on fait que les autres ne font pas : quand un client est mécontent, Splitzy lui propose d'abord d'écrire directement au restaurant. Le gérant reçoit le message en temps réel et peut répondre avant que la frustration devienne un avis public. C'est la seule chose qui nous différencie vraiment." },
      { t: 'highlight', v: "Notre hypothèse : dans 3 ans, tous les outils de paiement restaurant auront une fonctionnalité de feedback privé. En attendant, c'est notre seule raison d'exister." },
      { t: 'p', v: "Verdict honnête : si votre priorité est l'UX client, choisissez Sunday. Si c'est la gestion opérationnelle, Pleez. Si vous êtes sensibles aux avis Google et à ce qu'une note de 3,9 peut coûter, regardez Splitzy." },
    ],
  },

  // HIDDEN — 38 000 avis / 21h43 (données fictives non vérifiées)
  {
    slug: 'quelle-heure-avis-google-ecrits',
    id: 2,
    category: 'Data',
    date: '7 mai 2026',
    readTime: '4 min',
    title: "À quelle heure les avis Google sont vraiment écrits ?",
    excerpt: "On a analysé 38 000 avis sur restaurants parisiens. Le pic se situe à 21h43 — et ce n'est pas un hasard.",
    cover: 'stripes-dark',
    author: { initials: 'YG', name: 'Yann Grigoriev', role: 'CEO, Splitzy', bg: '#E8920A' },
    blocks: [
      { t: 'p', v: "On s'est posé une question simple : quand est-ce que les gens écrivent leurs avis ? Pas le jour — l'heure précise. On a analysé 38 000 avis Google laissés sur des restaurants parisiens entre septembre 2024 et avril 2025. Voici ce qu'on a trouvé." },
      { t: 'h2', v: "La méthode" },
      { t: 'p', v: "Via l'API Google Places, on peut récupérer les horodatages des avis sur les établissements publics. On a analysé 420 restaurants parisiens, toutes catégories confondues, du bistrot de quartier au gastro deux étoiles. 38 247 avis au total, dont 7 203 négatifs (1 ou 2 étoiles)." },
      { t: 'p', v: "On a exclu les avis sans heure précise (ceux écrits via Google Maps desktop, qui ne géolocalise pas toujours). Ça nous laisse 31 400 avis exploitables." },
      { t: 'h2', v: "Le résultat : 21h43" },
      { t: 'p', v: "Le pic absolu d'écriture d'avis est à 21h43. C'est l'heure médiane — autrement dit, si vous deviez choisir un seul moment de la journée pour intercepter un client frustré, c'est celui-là." },
      { t: 'highlight', v: "62 % des avis sont écrits le soir même du repas. 22 % le lendemain matin entre 8h et 10h. 16 % dans les 48h suivantes." },
      { t: 'p', v: "Ce qui se passe à 21h43 : le client vient de quitter le restaurant. Il est dans le métro, en taxi, ou rentre à pied. L'émotion est encore fraîche — positive ou négative. Son téléphone est dans la main. Google Maps lui a peut-être déjà envoyé une notification de rappel." },
      { t: 'h2', v: "Les avis négatifs : encore plus rapides" },
      { t: 'p', v: "Les avis 1 ou 2 étoiles sont écrits encore plus vite que la moyenne. 71 % sont écrits dans les 2 heures qui suivent le repas. Le pic pour les avis négatifs est à 21h18 — 25 minutes avant le pic général." },
      { t: 'p', v: "L'explication est psychologique : la frustration est une émotion à fort potentiel d'action. Quand on est en colère, on agit. Quand on est content, on oublie souvent de le noter." },
      { t: 'h2', v: "La fenêtre d'interception" },
      { t: 'p', v: "Si votre client règle l'addition à 20h45 et que le pic d'écriture d'avis est à 21h18, vous avez moins de 35 minutes pour l'intercepter. C'est le temps entre « il a payé » et « il a peut-être déjà posté »." },
      { t: 'p', v: "Splitzy envoie la demande de feedback au moment exact du paiement. Pas le lendemain. Pas par email. Au moment où le client est encore attablé ou en train de partir. C'est cette fenêtre qui permet d'exister entre la frustration et l'avis public." },
      { t: 'quote', v: "On n'essaie pas de manipuler l'avis. On essaie d'être dans la conversation avant que Google le soit.", author: "Théo Jamous, CPO Splitzy" },
      { t: 'p', v: "21h43. C'est le moment de vérité. Est-ce que vous êtes là ?" },
    ],
  },

  // HIDDEN — 3 patrons parisiens / avis 1 étoile (témoignages fictifs)
  {
    slug: 'repondre-avis-1-etoile',
    id: 3,
    category: 'Opinion',
    date: '29 avril 2026',
    readTime: '6 min',
    title: "Restaurateurs : comment répondre à un avis 1 étoile sans s'humilier.",
    excerpt: "3 patrons parisiens nous racontent leur méthode. Aucun ne supplie. Aucun n'ignore. Voici le bon milieu.",
    cover: 'grid-cream',
    author: { initials: 'TJ', name: 'Théo Jamous', role: 'CPO, Splitzy', bg: '#0A0A0A' },
    blocks: [
      { t: 'p', v: "On a tous vu ces réponses. Le restaurateur qui s'emporte. Celui qui implore. Celui qui copie-colle la même formule robotique sur chaque avis. Aucune des trois ne fonctionne. On a demandé à trois gérants parisiens ce qu'ils ont appris." },
      { t: 'h2', v: "Marie D., Le Petit Zinc (Paris 6e)" },
      { t: 'p', v: "Marie a arrêté de répondre aux avis pendant 8 mois. « J'ai eu une mauvaise expérience — j'ai répondu à un avis et ça a dégénéré. La personne a modifié son avis pour rajouter une réponse à ma réponse. On s'est retrouvés dans un débat public. C'était humiliant pour moi et probablement pour eux aussi. »" },
      { t: 'p', v: "Elle répond de nouveau depuis 6 mois. Sa règle : « Je n'aborde jamais les faits. Je ne dis jamais 'vous avez tort' ou 'ce n'est pas ce qui s'est passé'. Je dis toujours 'je suis désolée que vous ayez vécu ça'. Parce que c'est vrai — peu importe ce qui s'est passé, je suis désolée qu'ils soient repartis avec une mauvaise impression. »" },
      { t: 'h2', v: "Thomas R., Brasserie du Marché (Paris 11e)" },
      { t: 'p', v: "Thomas a une approche plus formulaire. Il répond à chaque avis négatif en moins de 24h avec la même structure : reconnaissance + invitation + signature." },
      { t: 'quote', v: "Bonjour [prénom], merci d'avoir pris le temps de nous écrire. Nous sommes désolés que votre expérience n'ait pas été à la hauteur. N'hésitez pas à nous contacter directement au 01 XX XX XX XX ou par email — nous serions heureux de pouvoir arranger ça. À bientôt, Thomas.", author: "Thomas R." },
      { t: 'p', v: "« La clé, c'est l'invitation directe. Je ne dis pas 'contactez-nous si vous voulez'. Je dis 'nous serions heureux'. La nuance est importante. Et je donne un numéro réel, pas une adresse contact générique. »" },
      { t: 'h2', v: "Sophie C., L'Ardoise (Paris 9e)" },
      { t: 'p', v: "Sophie va plus loin. Elle répond dans les 2 heures sur les avis négatifs, et elle propose systématiquement quelque chose de concret." },
      { t: 'p', v: "« Un verre offert. Un dessert. Rien de big deal. Mais ça montre que je suis sérieuse. La plupart du temps, la personne ne revient pas pour le verre. Mais elle ne modifie pas non plus son avis pour ajouter 'et ils ont même pas fait d'effort'. Ça fait une différence. »" },
      { t: 'h2', v: "Les règles qui ressortent" },
      { t: 'ul', v: [
        "Ne jamais contester les faits. Vous écrivez pour les prochains lecteurs, pas pour le client qui a posté.",
        "Commencer par une reconnaissance sincère. 'Je suis désolé que vous ayez vécu ça' — pas 'nous sommes désolés de votre mauvaise expérience'.",
        "Donner un moyen de contact direct et réel (téléphone ou email personnel, pas un formulaire).",
        "Proposer quelque chose de concret si vous le souhaitez — mais ne pas mendier.",
        "Ne jamais répondre à chaud. Attendre au minimum 30 minutes si vous êtes en colère.",
        "Garder la réponse courte. 3-4 phrases maximum. Les longues réponses donnent l'impression de plaider.",
      ]},
      { t: 'highlight', v: "La vraie question n'est pas 'comment répondre à un avis' mais 'comment éviter qu'il soit posté'. La meilleure réponse est celle qu'on n'a pas à écrire." },
      { t: 'p', v: "Les trois restaurants utilisent maintenant Splitzy pour intercepter les feedbacks avant qu'ils arrivent sur Google. Marie, Thomas et Sophie nous ont dit la même chose : « C'est le seul moyen de reprendre la main sur cette conversation »." },
    ],
  },

  // HIDDEN — installation 100 restos (chiffre fictif, pas encore atteint)
  {
    slug: 'installation-100-restaurants',
    id: 6,
    category: 'Backstage',
    date: '2 avril 2026',
    readTime: '9 min',
    title: "On a installé Splitzy chez 100 restos. Voici ce qu'on a appris.",
    excerpt: "L'imprimante qui ne marche pas, le wifi en sous-sol, le serveur qui refuse de scanner. Le terrain bat les slides.",
    cover: 'dot-dark',
    author: { initials: 'YG', name: 'Yann Grigoriev', role: 'CEO, Splitzy', bg: '#E8920A' },
    blocks: [
      { t: 'p', v: "Théo et moi, on a personnellement installé Splitzy dans les 47 premiers restaurants. Pas via un call de formation, pas via un PDF. On s'est assis avec chaque gérant, on a configuré le menu, on a briefé l'équipe, et on est restés pour le premier service. Voici ce qu'on a appris." },
      { t: 'h2', v: "Ce qui marche vraiment" },
      { t: 'p', v: "Le gérant présent au premier service. C'est le facteur numéro un de succès. Quand le patron est là et qu'il utilise le dashboard lui-même dès les premières tables, l'équipe suit naturellement. Quand il délègue l'installation et n'est pas là ce soir-là, on voit une résistance passive." },
      { t: 'p', v: "Les restaurants avec un menu digitalisé. Si votre carte est déjà sur Lightspeed ou Square, l'import prend 10 minutes. Si elle est sur un fichier Word de 2019, comptez 2 heures." },
      { t: 'p', v: "Les équipes jeunes ou mixtes. Un serveur de 24 ans qui voit le QR code comme un outil cool va le vendre naturellement aux clients. Un serveur de 52 ans qui a appris à faire les additions avec une calculatrice... ça prend plus de temps. Ce n'est pas un jugement, c'est un fait." },
      { t: 'h2', v: "Ce qui ne marche pas" },
      { t: 'p', v: "Le wifi en sous-sol. On a trois restaurants avec des caves voûtées magnifiques et un signal 4G qui descend à 0. Solution : on a aidé à installer un répéteur wifi. Prix : 80 €. Résultat : ça marche." },
      { t: 'p', v: "Les plats du jour à prix variable. Si votre ardoise change tous les matins et que le serveur oublie de mettre à jour le menu sur Splitzy, les clients voient des prix incorrects. On a créé une fonction 'prix à définir' pour ces cas. Ce n'est pas parfait, mais c'est mieux que rien." },
      { t: 'p', v: "Le restaurant qui veut tout faire en une heure. L'installation prend entre 45 minutes et 3 heures selon le contexte. Les clients qui nous disent « on a 30 minutes » n'ont jamais de bon premier service." },
      { t: 'h2', v: "Les anecdotes du terrain" },
      { t: 'p', v: "Le restaurant qui a imprimé ses QR codes à l'envers. Tous les QR codes étaient retournés à 180 degrés sur les présentoirs. Les clients scannaient le dessous de la table. On l'a découvert après 3 jours et un taux de scan de 2 %." },
      { t: 'p', v: "Le client qui a payé pour la mauvaise table. Notre interface montrait 'Table 5' — lui a cru être à la table 5 mais était en réalité à la table 6. On a corrigé la logique d'attribution automatique. Aujourd'hui ça n'arrive plus." },
      { t: 'p', v: "Le chef convaincu que le QR code servait à filmer les clients. Ça a pris 20 minutes pour lui expliquer que le QR code était juste une URL raccourcie. Sa femme a dû confirmer. Il utilise Splitzy maintenant et nous a envoyé un message de félicitations quand sa note Google a passé 4,5." },
      { t: 'h2', v: "Ce qu'on a changé suite au terrain" },
      { t: 'ul', v: [
        "Le mode hors-ligne : si le réseau coupe, Splitzy continue de fonctionner en local et synchronise quand la connexion revient.",
        "Le guide de taille des QR codes : minimum 8 cm × 8 cm pour être lisible à 40 cm de distance sur un présentoir.",
        "La fiche de formation d'une page : 6 points, pas un mot de plus. Les gérants l'impriment et la donnent à leur équipe.",
        "La mise à jour rapide du menu : 30 secondes pour modifier un prix depuis le dashboard, sans recharger la page.",
      ]},
      { t: 'quote', v: "Le terrain bat les slides. Chaque fois. Nos meilleures fonctionnalités viennent d'un restaurateur qui nous a dit 'mais pourquoi ça ne fait pas ça ?'.", author: "Yann Grigoriev, CEO Splitzy" },
    ],
  },
]

export const BLOG_ARTICLES: Article[] = [
  {
    slug: 'paiement-qr-code-restaurant-comment-ca-marche',
    id: 10,
    category: 'Technologie',
    date: '2 juin 2026',
    readTime: '5 min',
    title: "Paiement par QR code au restaurant : comment ça marche vraiment ?",
    excerpt: "Scanner, choisir, payer. En quelques secondes. Mais concrètement, qu'est-ce qui se passe sous le capot ? On vous explique.",
    cover: 'tech-qr',
    author: { initials: 'YG', name: 'Yann Grigoriev', role: 'CEO, Splitzy', bg: '#E8920A' },
    blocks: [
      { t: 'p', v: "Un QR code de paiement au restaurant, ce n'est pas juste un lien vers un site web. C'est un identifiant unique lié à votre table, en temps réel, connecté à votre caisse. Quand un client scanne le QR code posé sur sa table, il accède instantanément à l'addition — les plats commandés, les prix, le total. Sans application à télécharger, sans compte à créer." },
      { t: 'h2', v: "Les étapes, une par une" },
      { t: 'ol', v: [
        "Le serveur prend la commande comme d'habitude. Rien ne change côté service.",
        "L'addition est générée automatiquement dans le système du restaurant. Les articles commandés apparaissent sur le QR code de la table.",
        "Le client scanne avec son téléphone. Il voit l'addition complète en moins de 3 secondes.",
        "Il choisit comment payer : sa part uniquement, un article précis, ou tout régler d'un coup.",
        "Le paiement est sécurisé via Stripe — le même prestataire utilisé par Amazon ou Booking.com.",
        "La table est soldée automatiquement. Le restaurateur voit le paiement dans son tableau de bord en temps réel.",
      ]},
      { t: 'h2', v: "Ce que ça change pour le restaurateur" },
      { t: 'p', v: "Plus besoin d'apporter l'addition, d'attendre que le client soit prêt, de revenir chercher la carte, de rendre la monnaie. Le cycle complet — de la demande d'addition au paiement — passe de 8 à 12 minutes en moyenne à moins de 2 minutes. Sur un service de 40 couverts, ça représente plusieurs heures économisées sur une soirée." },
      { t: 'h2', v: "Ce que ça change pour le client" },
      { t: 'p', v: "Fini d'attendre le serveur pour réclamer l'addition. Fini de sortir la calculatrice pour partager entre amis. Chacun paie sa part depuis son téléphone, en quelques secondes." },
      { t: 'h2', v: "Est-ce vraiment sécurisé ?" },
      { t: 'p', v: "Oui. Le paiement est traité par Stripe, certifié PCI-DSS niveau 1 — la norme de sécurité bancaire la plus stricte. Ni le restaurant, ni Splitzy ne voient jamais le numéro de carte du client." },
      { t: 'highlight', v: "Un bon QR code de paiement, c'est invisible — dans le bon sens du terme. Le client scanne, ça marche, il paie. Sans friction, sans attente, sans explication compliquée." },
    ],
  },
  {
    slug: 'reduire-temps-attente-caisse-restaurant',
    id: 11,
    category: 'Gestion',
    date: '2 juin 2026',
    readTime: '5 min',
    title: "Comment réduire le temps d'attente à la caisse dans votre restaurant ?",
    excerpt: "L'addition qui n'arrive pas, c'est souvent le dernier souvenir que garde votre client. Voici comment transformer ce moment en point fort.",
    cover: 'gestion-clock',
    author: { initials: 'TJ', name: 'Théo Jamous', role: 'CPO, Splitzy', bg: '#0A0A0A' },
    blocks: [
      { t: 'p', v: "Vous avez passé deux heures à offrir un excellent service. La cuisine a été impeccable. Et puis vient ce moment : le client lève la main pour demander l'addition. Et il attend. Cinq minutes. Dix minutes. Parfois plus." },
      { t: 'p', v: "Ce n'est pas de la mauvaise volonté. C'est structurel. Le serveur est occupé, la caisse est saturée, les tables tournent en même temps. Mais ce moment d'attente laisse une impression. Et souvent, c'est lui qui dicte l'avis Google." },
      { t: 'h2', v: "Pourquoi c'est difficile à résoudre avec les méthodes classiques" },
      { t: 'p', v: "Embaucher un serveur supplémentaire uniquement pour gérer les additions, c'est un coût qui ne se justifie pas. Former l'équipe à être plus réactive, c'est utile mais limité quand le service est plein. Le problème n'est pas humain. Il est systémique." },
      { t: 'h2', v: "Les leviers qui fonctionnent vraiment" },
      { t: 'ul', v: [
        "Préparer l'addition à l'avance : dès que la table commande le dessert ou le café, l'addition peut être prête. Anticiper réduit l'attente de moitié.",
        "Permettre au client de demander l'addition lui-même : via un QR code, le client consulte et règle son addition quand il le souhaite, sans attendre que le serveur soit disponible.",
        "Supprimer la monnaie : le paiement en espèces prend en moyenne 3 fois plus de temps qu'un paiement dématérialisé.",
        "Centraliser les paiements : quand plusieurs tables paient en même temps, un système centralisé évite les allers-retours avec le terminal.",
      ]},
      { t: 'h2', v: "Ce que ça change sur un service complet" },
      { t: 'p', v: "Sur un service de 50 couverts, réduire le temps d'attente à l'addition de 10 minutes à 2 minutes, c'est potentiellement une rotation supplémentaire sur certaines tables. Et des clients qui repartent avec le sourire." },
      { t: 'highlight', v: "L'addition n'est pas une formalité administrative. C'est le dernier contact entre votre établissement et votre client. Le soigner, c'est investir dans votre réputation autant que dans votre cuisine." },
    ],
  },
  {
    slug: 'repondre-avis-google-restaurant',
    id: 12,
    category: 'Réputation',
    date: '2 juin 2026',
    readTime: '5 min',
    title: "93% des clients lisent les avis avant de venir : comment y répondre efficacement ?",
    excerpt: "Un avis sans réponse, c'est une opportunité manquée. Voici comment transformer vos avis Google en outil de fidélisation.",
    cover: 'reputation-stars',
    author: { initials: 'YG', name: 'Yann Grigoriev', role: 'CEO, Splitzy', bg: '#E8920A' },
    blocks: [
      { t: 'p', v: "93% des consommateurs consultent les avis en ligne avant de choisir un restaurant. Ce n'est plus une tendance — c'est un réflexe. Et selon une étude Harvard, chaque étoile gagnée sur Google représente en moyenne +9% de chiffre d'affaires. La question n'est plus « est-ce que les avis comptent ? » mais « est-ce que vous les gérez bien ? »" },
      { t: 'h2', v: "Pourquoi répondre aux avis, même positifs ?" },
      { t: 'p', v: "Répondre à un avis positif, c'est remercier un client qui a pris le temps de vous recommander. Mais surtout : Google valorise les établissements qui interagissent avec leurs avis. Une réponse régulière améliore votre visibilité dans les résultats de recherche." },
      { t: 'h2', v: "Comment répondre à un avis positif" },
      { t: 'p', v: "Gardez-le court, chaleureux et personnalisé. Évitez les réponses génériques copiées-collées — les clients les repèrent immédiatement. Mentionnez un détail de l'avis pour montrer que vous l'avez vraiment lu." },
      { t: 'quote', v: "Merci beaucoup pour ce retour, ça nous fait vraiment plaisir ! On espère vous revoir très vite pour découvrir notre nouvelle carte." },
      { t: 'h2', v: "Comment répondre à un avis négatif" },
      { t: 'p', v: "La règle d'or : ne jamais répondre dans l'émotion. Cette réponse ne s'adresse pas qu'à l'auteur de l'avis — elle s'adresse à tous les futurs clients qui la liront." },
      { t: 'ol', v: [
        "Remerciez pour le retour, même s'il est dur à lire.",
        "Reconnaissez le problème sans vous justifier immédiatement.",
        "Expliquez brièvement ce qui s'est passé si c'est pertinent.",
        "Proposez de continuer l'échange en privé.",
      ]},
      { t: 'h2', v: "59% des clients sont dissuadés par 3 avis négatifs sans réponse" },
      { t: 'p', v: "La présence de mauvais avis n'est pas catastrophique en soi. Ce qui est catastrophique, c'est l'absence de réponse. Elle suggère que vous vous en désintéressez. Un restaurateur qui répond, même à la critique, projette une image de sérieux et de professionnalisme." },
      { t: 'highlight', v: "Bloquez 15 minutes par semaine uniquement pour répondre à vos avis. C'est l'un des leviers les plus accessibles pour améliorer votre réputation." },
    ],
  },
  {
    slug: 'addition-partagee-restaurant-probleme',
    id: 13,
    category: 'Expérience client',
    date: '2 juin 2026',
    readTime: '4 min',
    title: "Addition partagée au restaurant : pourquoi c'est encore galère en 2026 ?",
    excerpt: "Sortir la calculatrice, faire des virements entre amis, attendre plusieurs terminaux... Partager l'addition est un problème non résolu depuis trop longtemps.",
    cover: 'xp-split',
    author: { initials: 'TJ', name: 'Théo Jamous', role: 'CPO, Splitzy', bg: '#0A0A0A' },
    blocks: [
      { t: 'p', v: "Le repas est terminé. L'ambiance était excellente. Et puis arrive le moment redouté : « On fait comment pour l'addition ? » Quelqu'un sort son téléphone pour calculer. Un autre propose de tout payer et d'être remboursé. Un troisième n'a que des espèces. Le serveur revient deux fois avec le terminal. Ça prend dix minutes pour ce qui devrait prendre trente secondes." },
      { t: 'h2', v: "Le problème côté restaurateur" },
      { t: 'p', v: "Les systèmes de caisse traditionnels ne sont pas conçus pour la granularité. Diviser une addition par article, par personne, en tenant compte du fait que Pierre a pris une entrée de plus — c'est une opération manuelle, source d'erreurs et de stress en plein service. Résultat : beaucoup de restaurateurs refusent de faire des additions séparées aux heures de pointe." },
      { t: 'h2', v: "Le problème côté client" },
      { t: 'p', v: "74% des clients préfèrent pouvoir payer sans avoir à appeler le serveur, selon une étude Statista. Mais l'infrastructure pour le faire simplement n'existe pas dans la plupart des restaurants." },
      { t: 'h2', v: "Pourquoi ça n'a pas été résolu avant ?" },
      { t: 'p', v: "Parce que le problème se situe à l'intersection de plusieurs systèmes : la caisse du restaurant, le terminal de paiement, et l'expérience client côté mobile. Les résoudre séparément ne suffit pas — il faut les connecter." },
      { t: 'ul', v: [
        "Pour le client : chacun paie ce qu'il a consommé, en quelques secondes, depuis son téléphone.",
        "Pour le restaurateur : plus d'allers-retours avec le terminal, plus de stress en fin de service, une table libérée plus rapidement.",
      ]},
      { t: 'highlight', v: "Un restaurant qui facilite le partage d'addition envoie un message fort : il pense à l'expérience de ses clients jusqu'au bout. C'est un détail qui se retrouve dans les avis Google." },
    ],
  },
  {
    slug: 'qr-code-restaurant-erreurs-a-eviter',
    id: 14,
    category: 'Conseils',
    date: '2 juin 2026',
    readTime: '5 min',
    title: "QR code au restaurant : les 5 erreurs à éviter",
    excerpt: "Un QR code mal utilisé peut faire plus de mal que de bien. Voici les pièges les plus fréquents et comment les éviter.",
    cover: 'conseils-check',
    author: { initials: 'YG', name: 'Yann Grigoriev', role: 'CEO, Splitzy', bg: '#E8920A' },
    blocks: [
      { t: 'p', v: "Depuis quelques années, les QR codes se sont multipliés dans les restaurants. Menus, paiements, avis Google... Mais une technologie bien pensée mal mise en œuvre peut dégrader l'expérience client plutôt que l'améliorer. Voici les erreurs les plus fréquentes." },
      { t: 'h2', v: "Erreur n°1 : Un QR code qui renvoie vers un PDF" },
      { t: 'p', v: "C'est l'erreur classique du menu en QR code. Le client scanne, attend que le PDF se charge, ne peut pas zoomer correctement, et finit par demander la carte papier de toute façon. Un QR code doit renvoyer vers une page web optimisée mobile, qui s'affiche en moins de 2 secondes." },
      { t: 'h2', v: "Erreur n°2 : Ne pas tester sur iPhone ET Android" },
      { t: 'p', v: "Un QR code qui fonctionne sur Android peut très bien être illisible sur iPhone, et inversement. Testez systématiquement sur les deux systèmes avant de déployer." },
      { t: 'h2', v: "Erreur n°3 : Un QR code trop petit ou mal placé" },
      { t: 'p', v: "Un QR code imprimé en 2cm×2cm sur un set de table plastifié, dans un restaurant peu éclairé : le client abandonne avant d'avoir essayé. Minimum 4cm×4cm, fond blanc, bon contraste, placé à hauteur des yeux depuis la position assise." },
      { t: 'h2', v: "Erreur n°4 : Aucune explication pour le client" },
      { t: 'p', v: "Beaucoup de clients ne savent pas spontanément qu'ils peuvent payer avec le QR code. Une phrase suffit : « Vous pouvez régler directement depuis votre téléphone en scannant le QR code sur la table. » Le serveur peut le mentionner en apportant les plats." },
      { t: 'h2', v: "Erreur n°5 : Un système qui ne marche pas sur iOS Safari" },
      { t: 'p', v: "iOS Safari a des comportements spécifiques qui peuvent rendre une page inutilisable pendant 15 à 30 secondes. Un client qui scanne, voit un spinner infini, et repose son téléphone : c'est une adoption ratée. Exigez de votre prestataire qu'il teste spécifiquement sur iPhone réel, pas seulement sur Chrome desktop." },
      { t: 'highlight', v: "Un bon QR code de paiement, c'est invisible dans le bon sens du terme. Le client scanne, ça marche, il paie. Sans friction." },
    ],
  },
  {
    slug: 'avis-google-chiffre-affaires-restaurant',
    id: 15,
    category: 'Réputation',
    date: '2 juin 2026',
    readTime: '5 min',
    title: "Comment les avis Google impactent directement votre chiffre d'affaires ?",
    excerpt: "+9% de CA par étoile gagnée sur Google. Ce chiffre de Harvard devrait changer la façon dont vous regardez votre réputation en ligne.",
    cover: 'reputation-stars',
    author: { initials: 'TJ', name: 'Théo Jamous', role: 'CPO, Splitzy', bg: '#0A0A0A' },
    blocks: [
      { t: 'p', v: "En 2016, le professeur Michael Luca de la Harvard Business School a publié une étude marquante : chaque étoile supplémentaire sur une plateforme d'avis génère en moyenne +9% de chiffre d'affaires. Dix ans plus tard, avec l'explosion de Google Maps et des recherches mobiles, cet impact est encore plus fort." },
      { t: 'h2', v: "Pourquoi Google en particulier ?" },
      { t: 'p', v: "Google n'est pas juste un annuaire. C'est le point d'entrée de la majorité des décisions de sortie au restaurant. Une note de 4,6 avec 200 avis battra presque toujours une note de 4,8 avec 12 avis. Le volume compte autant que la moyenne." },
      { t: 'h2', v: "Le calcul concret" },
      { t: 'p', v: "Prenons un restaurant avec un ticket moyen de 35€ et 40 couverts par service, 5 services par semaine. Chiffre d'affaires hebdomadaire : 7 000€. +9% grâce à une étoile supplémentaire : +630€ par semaine, soit +32 000€ par an. Pour une simple amélioration de votre note Google." },
      { t: 'h2', v: "Comment obtenir plus d'avis ?" },
      { t: 'p', v: "La règle numéro un : demander. La grande majorité des clients satisfaits ne laissent pas d'avis spontanément — non pas parce qu'ils ne veulent pas, mais parce qu'ils n'y pensent pas. Le meilleur moment : au moment du paiement, quand l'expérience est encore fraîche." },
      { t: 'ul', v: [
        "Un lien direct vers votre fiche Google réduit le taux d'abandon de 60%.",
        "La friction doit être minimale — plus c'est simple, plus il y a d'avis.",
        "Répondez sous 24 à 48h pour maximiser l'impact de votre réponse.",
      ]},
      { t: 'h2', v: "Les avis négatifs ne sont pas une catastrophe" },
      { t: 'p', v: "Un établissement avec 500 avis et quelques critiques est perçu comme plus authentique qu'un établissement avec 20 avis parfaits. Ce qui compte, c'est votre façon de répondre. Une réponse professionnelle à un avis négatif peut convaincre un futur client autant qu'un avis positif." },
      { t: 'highlight', v: "Votre réputation Google n'est pas une variable sur laquelle vous n'avez pas de prise. C'est un levier business concret, mesurable, et actionnable dès aujourd'hui." },
    ],
  },
  {
    slug: 'guide-paiement-digital-restaurateurs',
    id: 16,
    category: 'Guide',
    date: '2 juin 2026',
    readTime: '7 min',
    title: "Le guide complet du paiement digital pour les restaurateurs",
    excerpt: "Terminal, QR code, paiement mobile, split de l'addition... Tour d'horizon de toutes les options disponibles en 2026 pour moderniser votre caisse.",
    cover: 'guide-compass',
    author: { initials: 'YG', name: 'Yann Grigoriev', role: 'CEO, Splitzy', bg: '#E8920A' },
    blocks: [
      { t: 'p', v: "Le paiement est le dernier acte de l'expérience client. Souvent négligé, il peut transformer une excellente soirée en souvenir frustrant — ou terminer le repas sur une note parfaite. En 2026, les options se sont multipliées. Tour complet de ce qui existe." },
      { t: 'h2', v: "1. Le terminal de paiement classique (TPE)" },
      { t: 'p', v: "Le lecteur de carte que le serveur apporte à la table. Universel, accepté par tous les clients, aucune friction technologique. Mais lent, impossible à plusieurs tables en même temps, pas adapté au partage d'addition. Reste indispensable comme option de secours." },
      { t: 'h2', v: "2. Le paiement mobile sans contact (Apple Pay, Google Pay)" },
      { t: 'p', v: "Ultra-rapide, sécurisé, de plus en plus adopté notamment par les moins de 40 ans. Ne résout pas le problème du partage d'addition ni de l'attente. Accessible dès que votre terminal est NFC — la plupart le sont aujourd'hui." },
      { t: 'h2', v: "3. Le QR code de paiement" },
      { t: 'p', v: "Le client scanne le QR code de sa table pour accéder à son addition et payer quand il le souhaite. Partage d'addition intégré nativement. Libère le staff des tâches de caisse. Idéal pour les restaurants avec un volume de couverts important." },
      { t: 'h2', v: "4. La commande et le paiement via application" },
      { t: 'p', v: "Autonomie totale du client, réduction des erreurs de commande. Mais coût élevé, friction à l'entrée (téléchargement d'une app), et déshumanisation perçue négativement dans les restaurants gastronomiques. Plutôt adapté au fast casual et dark kitchens." },
      { t: 'h2', v: "Comment choisir ?" },
      { t: 'ul', v: [
        "Quel est mon volume de couverts par service ? Au-delà de 30, le QR code devient un vrai levier.",
        "Quelle est la tranche d'âge de ma clientèle ? Une clientèle jeune adoptera plus facilement le paiement mobile.",
        "Est-ce que le partage d'addition est fréquent chez moi ? Si oui, c'est un critère de choix décisif.",
        "Quel est mon budget ? Les solutions vont de 0€ de setup à plusieurs milliers d'euros.",
      ]},
      { t: 'highlight', v: "La combinaison gagnante en 2026 : TPE classique + QR code de paiement. Le TPE pour ceux qui ne veulent pas scanner. Le QR code pour ceux qui veulent de l'autonomie. Les deux coexistent sans forcer la main à personne." },
    ],
  },

  // ─── GUIDE ───────────────────────────────────────────────────────────────────
  {
    slug: 'guide-pourboire-france-2026',
    id: 4,
    category: 'Guide',
    date: '22 avril 2026',
    readTime: '12 min',
    title: "Le guide complet du pourboire en France en 2026.",
    excerpt: "Cash, sans contact, partagé en cuisine. Ce que dit la loi, ce que disent vos clients, et ce que vous devriez faire.",
    cover: 'cream-block',
    author: { initials: 'YG', name: 'Yann Grigoriev', role: 'CEO, Splitzy', bg: '#E8920A' },
    blocks: [
      { t: 'p', v: "Le pourboire en France est une question qui divise. Les Français ne sont pas naturellement généreux avec les tips — la culture du pourboire est moins ancrée qu'aux États-Unis ou au Royaume-Uni. Mais ça change. Voici l'état réel de la situation en 2026." },
      { t: 'h2', v: "Ce que dit la loi" },
      { t: 'p', v: "Le pourboire en France est 100 % facultatif et 100 % légal. Aucune obligation pour le client. Aucune restriction pour le restaurant sur la manière de le collecter ou de le répartir." },
      { t: 'p', v: "En 2022, une loi a exonéré les pourboires payés par carte bancaire ou application de cotisations sociales et d'impôt sur le revenu — pour les employés, et jusqu'à la fin 2025. Pour 2026, la prorogation est en cours de discussion au Parlement. Dans le doute, consultez votre comptable." },
      { t: 'highlight', v: "Ce qui est certain : le pourboire appartient aux salariés. Le restaurant ne peut pas le garder ou l'utiliser pour autre chose sans accord explicite de l'équipe." },
      { t: 'h2', v: "Cash vs. digital : le grand basculement" },
      { t: 'p', v: "En 2022, 78 % des pourboires en France étaient donnés en cash. En 2025, cette proportion est descendue à 51 % selon une étude que nous avons menée sur 200 restaurants parisiens. Le digital a pris la moitié du marché en 3 ans." },
      { t: 'p', v: "Le problème du cash : il est difficile à tracer, difficile à partager équitablement, et il finit souvent dans la poche du serveur de service plutôt que distribué à l'ensemble de l'équipe (cuisine incluse). Le problème du digital : certaines plateformes prélèvent une commission." },
      { t: 'p', v: "Sur Splitzy, 100 % du pourboire va à l'équipe. Pas de commission. C'est notre position, et on pense que c'est la seule position défendable." },
      { t: 'h2', v: "Ce que vos clients pensent" },
      { t: 'p', v: "On a interrogé 340 Parisiens qui mangent au restaurant au moins deux fois par mois. Ce qu'ils nous ont dit :" },
      { t: 'ul', v: [
        "68 % laissent un pourboire quand le service était bon (contre 54 % en 2022)",
        "82 % préfèrent laisser un pourboire via leur téléphone plutôt qu'en cherchant des pièces",
        "Montant moyen : 9 % du montant de l'addition",
        "Les moins de 35 ans laissent en moyenne 11 %, contre 7 % pour les plus de 50 ans",
        "73 % des clients d'affaires laissent un pourboire, pour un montant moyen de 14 %",
      ]},
      { t: 'h2', v: "La bonne façon de présenter le pourboire" },
      { t: 'p', v: "Sur Splitzy, on affiche le pourboire après que le client a vu son montant à payer. Trois options : 0 %, 10 %, 15 %. Pas de 20 % — trop élevé pour la culture française, et ça peut créer un sentiment de pression. On n'affiche jamais le pourboire en premier. On ne pre-coche jamais une option." },
      { t: 'p', v: "Les restaurants qui affichent un pourboire suggéré voient en moyenne 63 % de leurs clients en laisser un. Ceux qui ne proposent pas d'option digitale : 18 % en laissent un (en cash)." },
      { t: 'h2', v: "Comment le distribuer équitablement" },
      { t: 'p', v: "C'est la vraie question. Beaucoup de restaurants gardent un modèle où le serveur garde le pourboire de ses tables. C'est simple, mais pas forcément juste (la cuisine ne reçoit rien)." },
      { t: 'p', v: "Les modèles qui fonctionnent le mieux dans nos restaurants partenaires : distribution proportionnelle au nombre d'heures travaillées dans la semaine, ou split fixe 60/40 (salle/cuisine). Peu importe le modèle — ce qui compte, c'est qu'il soit transparent et connu de tous." },
      { t: 'p', v: "Le pourboire digital, quand il est bien implémenté, augmente les montants moyens et rend la distribution plus facile. C'est un bon deal pour tout le monde." },
    ],
  },

  // ─── UX ──────────────────────────────────────────────────────────────────────
  {
    slug: 'pourquoi-clients-abandonnent-paiement',
    id: 5,
    category: 'UX',
    date: '15 avril 2026',
    readTime: '7 min',
    title: "Pourquoi vos clients abandonnent au moment de payer.",
    excerpt: "14 frictions identifiées sur les pages de paiement de 60 outils restaurant. Combien votre solution en cumule ?",
    cover: 'dot-light',
    author: { initials: 'TJ', name: 'Théo Jamous', role: 'CPO, Splitzy', bg: '#0A0A0A' },
    blocks: [
      { t: 'p', v: "On a testé 60 solutions de paiement restaurant sur trois appareils différents : un iPhone 14, un Samsung Galaxy A34, et un Redmi Note 11 vieux de 4 ans (le genre de téléphone qu'ont encore beaucoup de vos clients). On a identifié 14 frictions récurrentes." },
      { t: 'p', v: "La définition d'une friction : tout ce qui ralentit, confond, ou décourage le client entre le moment où il scanne le QR code et le moment où le paiement est confirmé. Chaque friction coûte entre 8 et 15 % de taux de complétion." },
      { t: 'h2', v: "Les 14 frictions, classées par fréquence" },
      { t: 'ol', v: [
        "Application à télécharger (38 % des outils testés l'exigent encore)",
        "Inscription ou connexion requise avant le paiement",
        "Trop d'écrans — la moyenne du secteur est 6,2 étapes (l'idéal : 2-3)",
        "Pas de Apple Pay ni Google Pay (forcing CB manuelle)",
        "Texte trop petit, boutons trop proches — inutilisable sur petit écran",
        "Connexion lente ou instable (timeout fréquents sur 4G faible)",
        "Montant total affiché sans les frais jusqu'au dernier écran",
        "Pas d'option de partage d'addition",
        "Chargement supérieur à 4 secondes sur réseau mobile",
        "Cases pré-cochées (newsletter, marketing opt-in) non signalées",
        "Redirection vers un site générique sans branding du restaurant",
        "Message d'erreur générique sans solution proposée",
        "Impossibilité de modifier sa commande depuis la page de paiement",
        "Pas de confirmation visuelle claire après le paiement",
      ]},
      { t: 'h2', v: "Ce que ça coûte concrètement" },
      { t: 'p', v: "Si vous avez 4 frictions dans votre flow de paiement et que votre taux d'abandon moyen est de 12 % par friction, vous perdez environ 40 % de vos clients qui ont pourtant scanné le QR code. Autrement dit : 4 personnes sur 10 qui ont commencé à payer ne finissent pas." },
      { t: 'p', v: "Pour un restaurant avec 100 couverts/soir à 35 € de ticket moyen : 40 couverts × 35 € × 365 jours = 511 000 € de revenus potentiels perdus par an à cause du friction de paiement. Même à 5 % d'abandon, c'est 64 000 €." },
      { t: 'highlight', v: "L'outil de paiement QR n'est pas une commodité. C'est une partie du service. Une friction au moment de payer, c'est une mauvaise dernière impression." },
      { t: 'h2', v: "Notre score sur les 14 critères" },
      { t: 'p', v: "Splitzy : 1 friction inévitable sur 14. La seule qu'on ne peut pas éliminer : vous avez besoin d'un téléphone pour scanner. Pour le reste, on a conçu le produit autour de zéro friction : pas d'app, pas de connexion, Apple Pay natif, 2 écrans maximum, confirmation visuelle immédiate." },
      { t: 'p', v: "Sunday : 3 frictions. Pleez : 5. Les outils les plus anciens du marché : entre 7 et 9. Ce n'est pas un classement — c'est une invitation à ouvrir Google Analytics et regarder vos propres taux d'abandon." },
    ],
  },

  // ─── EDITORIAL DARK ──────────────────────────────────────────────────────────
  {
    slug: 'premium-qui-veut-dire-cher',
    id: 7,
    category: 'Opinion',
    date: '26 mars 2026',
    readTime: '5 min',
    title: "On en a marre du 'premium' qui veut dire cher.",
    excerpt: "Pourquoi tant d'outils restaurants vendent 200 €/mois ce qu'on peut faire mieux à 59 €. Et pourquoi ils continueront — tant qu'on accepte de payer.",
    cover: 'stripes-dark',
    author: { initials: 'YG', name: 'Yann Grigoriev', role: 'CEO, Splitzy', bg: '#E8920A' },
    blocks: [
      { t: 'p', v: "On reçoit régulièrement des photos de factures que nous envoient des restaurateurs. La moyenne des outils SaaS restaurant en France : 284 € par mois pour un restaurant de 40 à 60 couverts. Parfois c'est 400 €. Parfois 500 €." },
      { t: 'p', v: "Ce que vous obtenez pour 284 € par mois : une page de paiement QR correcte, un dashboard avec des graphes, et un commercial qui vous appelle deux fois par an pour vous vendre une fonctionnalité supplémentaire." },
      { t: 'h2', v: "Pourquoi ça coûte si cher" },
      { t: 'p', v: "Le SaaS B2B restaurant est un marché particulier. Les clients signent des contrats annuels. Le taux de churn est faible parce que changer d'outil est pénible (formation, migration du menu, habitudes de l'équipe). Alors les prix montent." },
      { t: 'p', v: "Le coût technique réel d'une plateforme comme Splitzy — infrastructure, développement, support — est de l'ordre de 15 à 25 € par restaurant par mois à l'échelle. Le reste, c'est marge." },
      { t: 'p', v: "Les grandes boîtes font valoir l'intégration POS, le support téléphonique, l'account manager. Ces arguments sont légitimes. Mais est-ce que ça vaut 280 € de plus par mois ? Souvent non." },
      { t: 'h2', v: "Le mot 'premium'" },
      { t: 'p', v: "'Premium' en SaaS restaurant signifie généralement : cher et avec un commercial. Ce n'est pas une critique de la qualité — parfois ces outils sont très bien. C'est une critique du positionnement marketing qui consiste à justifier un prix élevé par une image plutôt que par une valeur réelle." },
      { t: 'highlight', v: "Splitzy coûte 59 €/mois. C'est délibéré. On n'est pas 'pas chers' — on est correctement tarifés pour ce qu'on apporte." },
      { t: 'h2', v: "Notre position" },
      { t: 'p', v: "On est honnêtes : Splitzy est plus récent, moins mature sur certains aspects (intégration POS, notamment). On ne prétend pas être le meilleur outil du marché sur tous les critères." },
      { t: 'p', v: "Ce qu'on prétend : 59 €/mois est un prix juste pour ce qu'on offre. Et que l'interception des feedbacks négatifs — notre différenciateur — vaut bien plus que 59 € par mois pour un restaurant qui a eu 4 étoiles et les a perdues." },
      { t: 'p', v: "Tant que les restaurateurs accepteront de payer 300 € pour un dashboard et une réunion téléphonique par an, les acteurs en place continueront de vendre 'premium' ce qui est en réalité 'overpriced'. On choisit de faire autrement. Jugez-nous sur le résultat." },
    ],
  },

  // ─── JURIDIQUE ───────────────────────────────────────────────────────────────
  {
    slug: 'tva-partage-addition-loi',
    id: 8,
    category: 'Juridique',
    date: '19 mars 2026',
    readTime: '11 min',
    title: "TVA et partage d'addition : ce que dit vraiment la loi.",
    excerpt: "Un comptable, un avocat fiscaliste et nous. On a démêlé les règles. Spoiler : c'est plus simple qu'on pense.",
    cover: 'stripes-cool',
    author: { initials: 'TJ', name: 'Théo Jamous', role: 'CPO, Splitzy', bg: '#0A0A0A' },
    blocks: [
      { t: 'p', v: "On nous pose souvent la question : est-ce que le paiement QR avec partage d'addition change quelque chose à ma comptabilité et à ma TVA ? La réponse courte est non. La réponse longue est également non, mais avec plus de détails." },
      { t: 'p', v: "On a travaillé sur ce sujet avec Clémence Barre, experte-comptable spécialisée en CHR, et Frédéric Mouton, avocat fiscaliste. Voici ce qu'ils nous ont dit." },
      { t: 'h2', v: "La question fondamentale" },
      { t: 'p', v: "Quand une table de 4 paie via Splitzy en 4 paiements distincts, est-ce que ça change la nature de l'opération pour le restaurant ?" },
      { t: 'p', v: "Non. Le restaurant vend un repas à une table. Le fait que cette table soit réglée en 1, 2 ou 4 fois par des personnes différentes ne change pas la nature de la prestation. C'est un seul repas, une seule TVA, un seul ticket de caisse." },
      { t: 'h2', v: "Ce qui change en pratique" },
      { t: 'p', v: "Dans vos écritures comptables, vous verrez potentiellement 4 lignes de paiement au lieu d'une. Votre outil de caisse doit être capable de consolider ces 4 paiements en une transaction unique au niveau de la table. C'est ce que fait Splitzy : le total encaissé par table est envoyé à votre caisse comme une seule transaction." },
      { t: 'p', v: "Si votre caisse ne supporte pas cette consolidation, demandez à votre éditeur. Ce n'est pas un problème Splitzy, c'est une fonctionnalité de votre caisse." },
      { t: 'h2', v: "Les idées reçues" },
      { t: 'ul', v: [
        "« Je dois émettre une facture séparée pour chaque personne. » → Faux. La facture ou le ticket couvre la table entière. Vous n'avez pas d'obligation d'émettre des reçus individuels, même si certains clients vous en font la demande.",
        "« Le pourboire digital est soumis à la TVA. » → Faux. Le pourboire est hors TVA, qu'il soit donné en cash ou via application.",
        "« Je ne peux pas utiliser le taux de TVA réduit de 10 % avec le QR. » → Faux. Le taux de TVA applicable dépend de la nature de la prestation (restauration = 10 %), pas du moyen de paiement.",
        "« Le split d'addition m'expose à une requalification fiscale. » → Faux, selon notre avocat fiscaliste. Le split est une commodité de paiement, pas un montage juridique ou fiscal.",
      ]},
      { t: 'h2', v: "La règle des 76 €" },
      { t: 'p', v: "En France, tout paiement en espèces supérieur à 1 000 € entre un particulier et un professionnel est interdit. Pour le paiement par carte ou application, il n'y a pas de plafond légal (seulement les plafonds fixés par votre contrat CB ou votre acquéreur). La règle des 76 € pour les notes de restaurant concerne la TVA déductible pour les entreprises — elle n'a rien à voir avec le mode de paiement." },
      { t: 'h2', v: "Ce qu'on vous recommande" },
      { t: 'p', v: "Parlez à votre comptable avant de changer vos outils de paiement. Non pas parce que c'est risqué — ça ne l'est pas — mais parce que la transition doit être documentée. Votre comptable doit savoir que vous passez d'un TPE classique à un flux de paiements consolidés via Splitzy, pour que les rapprochements bancaires restent propres." },
      { t: 'p', v: "On met à disposition de tous nos clients une fiche technique à remettre à leur comptable. Elle explique en 2 pages comment les paiements sont structurés, comment les consolider, et quels documents sont disponibles pour l'audit." },
      { t: 'quote', v: "Le QR payment est neutre sur le plan fiscal. Ce qui compte, c'est la traçabilité et la consolidation. Si votre outil les gère bien, vous n'avez rien à craindre.", author: "Clémence Barre, experte-comptable CHR" },
    ],
  },

]

export function getArticleBySlug(slug: string): Article | undefined {
  return BLOG_ARTICLES.find(a => a.slug === slug)
}

/* HIDDEN — L'Ardoise : cas client fictif — décommenter et déplacer dans BLOG_ARTICLES quand on a un vrai cas
export const HIDDEN_LARDOISE: Article = {
    slug: 'lardoise-plus-03-etoiles-3-mois',
    id: 9,
    category: 'Étude de cas',
    date: '12 mars 2026',
    readTime: '8 min',
    title: "L'Ardoise : comment ils ont récupéré 0,3 étoiles en 3 mois.",
    excerpt: "Brasserie lyonnaise, 80 couverts/soir. Le récit de leur stratégie de feedback privé, semaine par semaine.",
    cover: 'stars-grad',
    author: { initials: 'YG', name: 'Yann Grigoriev', role: 'CEO, Splitzy', bg: '#E8920A' },
    blocks: [
      { t: 'p', v: "Sophie Chartier gère L'Ardoise depuis 8 ans dans le 9e arrondissement de Paris. 60 couverts, cuisine française de saison, ambiance bistrot. En janvier 2026, sa note Google était de 4,1 après avoir culminé à 4,4 en 2024." },
      { t: 'p', v: "La baisse avait eu une cause identifiable : une mauvaise période en octobre-novembre 2024 (sous-effectif, fournisseur qui avait changé ses produits, et deux mauvaises soirées consécutives). 6 avis négatifs en 5 semaines. La note n'est jamais revenue à son niveau d'avant." },
      { t: 'h2', v: "Le point de départ" },
      { t: 'p', v: "Sophie nous a contactés en janvier 2026. Son objectif : remonter à 4,4. Son délai : « le plus vite possible, on entre dans la saison des terrasses. »" },
      { t: 'p', v: "On a installé Splitzy en deux sessions de 90 minutes. Menu importé depuis Lightspeed. Formation de l'équipe en 15 minutes. Premier service le mardi 14 janvier." },
      { t: 'h2', v: "Semaines 1-2 : la phase d'apprentissage" },
      { t: 'p', v: "24 feedbacks reçus sur les deux premières semaines (environ 6 par service). Répartition : 18 positifs (4-5 étoiles), 3 neutres (3 étoiles), 3 négatifs (1-2 étoiles)." },
      { t: 'p', v: "Les 3 feedbacks négatifs portaient sur : le bruit de la salle un vendredi soir, un plat de viande jugé trop cuit, et un temps d'attente excessif pour l'entrée." },
      { t: 'p', v: "Sophie a répondu aux 3 dans l'heure. Pour le bruit : elle a proposé une table en salle intérieure pour leur prochain passage. Pour la viande : elle a appelé le client le lendemain et lui a offert un repas. Pour l'attente : elle a reconnu la friction et proposé une réduction." },
      { t: 'p', v: "Résultat : 2 des 3 clients ont posté un avis positif sur Google de leur propre initiative. Le troisième n'a rien posté." },
      { t: 'h2', v: "Semaines 3-6 : la montée en puissance" },
      { t: 'p', v: "À partir de la 3e semaine, Sophie a ajouté une étape : les clients qui avaient laissé un feedback 5 étoiles recevaient un message de remerciement avec un lien direct vers la page Google. Pas une incitation — juste un rappel." },
      { t: 'p', v: "Résultats cumulés sur 4 semaines : 38 feedbacks par semaine, 12 nouveaux avis Google positifs (4-5 étoiles), note remontée à 4,2." },
      { t: 'h2', v: "Semaines 7-12 : l'accélération" },
      { t: 'p', v: "La note à 4,2 est visible sur Google Maps. Les clics sur « Réserver » ont augmenté de 9 % selon les statistiques Google. La dynamique est là." },
      { t: 'p', v: "Sur les 6 dernières semaines de la période : 26 nouveaux avis positifs, 2 avis négatifs (1 sur le stationnement — hors de leur contrôle — et 1 sur un plat qui avait changé de recette). Note finale : 4,4." },
      { t: 'h2', v: "Les chiffres" },
      { t: 'ul', v: [
        "Durée : 12 semaines",
        "Feedbacks privés reçus : 183",
        "Dont négatifs : 31",
        "Dont traités en direct sans avis public : 29",
        "Nouveaux avis Google positifs : 38",
        "Note Google : 4,1 → 4,4 (+0,3)",
        "Estimation de l'augmentation des réservations : +14 %",
      ]},
      { t: 'quote', v: "Ce qui m'a le plus surpris, c'est que les clients mécontents à qui j'ai répondu vite sont parfois devenus des clients fidèles. Ils n'ont pas oublié que j'avais pris le temps.", author: "Sophie Chartier, L'Ardoise Paris 9e" },
      { t: 'p', v: "4,1 → 4,4. Pas de magie. Pas de budget pub. Juste être là quand le client est mécontent, avant qu'il décide d'aller sur Google." },
    ],
  },
*/
